export const WITHDRAWALS_FETCH_REQUEST = 'WITHDRAWALS_FETCH_REQUEST';
export const WITHDRAWALS_FETCH_SUCCESS = 'WITHDRAWALS_FETCH_SUCCESS';
export const WITHDRAWALS_FETCH_FAILURE = 'WITHDRAWALS_FETCH_FAILURE';
export const WITHDRAWALS_SET_RECENT_OPEN = 'WITHDRAWALS_SET_RECENT_OPEN';
export const WITHDRAWALS_CLEAR_ERROR = 'WITHDRAWALS_CLEAR_ERROR';

// New withdrawal creation constants
export const WITHDRAWAL_CREATE_REQUEST = 'WITHDRAWAL_CREATE_REQUEST';
export const WITHDRAWAL_CREATE_SUCCESS = 'WITHDRAWAL_CREATE_SUCCESS';
export const WITHDRAWAL_CREATE_FAILURE = 'WITHDRAWAL_CREATE_FAILURE';
export const WITHDRAWAL_CLEAR_CREATE_STATE = 'WITHDRAWAL_CLEAR_CREATE_STATE';
