export const FETCH_TASKS_REQUEST = 'task/FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'task/FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'task/FETCH_TASKS_FAILURE';

export const COMPLETE_TASK_REQUEST = 'task/COMPLETE_TASK_REQUEST';
export const COMPLETE_TASK_SUCCESS = 'task/COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE = 'task/COMPLETE_TASK_FAILURE';
