export const CREATE_USER_REQUEST = 'auth/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'auth/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'auth/CREATE_USER_FAILURE';

export const FETCH_USER_REQUEST = 'auth/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'auth/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'auth/FETCH_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'auth/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'auth/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'auth/UPDATE_USER_FAILURE';

export const CLEAR_AUTH_ERROR = 'auth/CLEAR_AUTH_ERROR';
export const LOGOUT_USER = 'auth/LOGOUT_USER';
export const RESET_AUTH_STATE = 'auth/RESET_AUTH_STATE';
